fixing go project

diff --git a/demogolang/bin/build b/demogolang/bin/build
--- a/demogolang/bin/build
+++ b/demogolang/bin/build
@@ -29,7 +29,7 @@ fi
 local INIT_DIR=$(pwd)
 local PROJECT_PATH="$1"
 local PROJECT_NAME=$(basename "$PROJECT_PATH")
-local BUILD_TARGET="$2/$PROJECT_NAME.tar.gz"
+local BUILD_TARGET="$2"
 local BUILD_VERSION="$3"
 
 if [ ! -d "$PROJECT_PATH" ]; then
@@ -42,24 +42,46 @@ if [ -f "$BUILD_TARGET" ]; then
   return  1
 fi
 
+# Create a temporary build directory
+BUILD_TMP_DIR="$(mktemp -d)"
+
+# full path of the output .tar.gz file = <out_dir(arg 2)>/<project_name>.tar.gz
+ARCHIVE_DST_PATH="$BUILD_TARGET/$PROJECT_NAME.tar.gz"
+
 printf "PACKAGE: %s\n" "$PROJECT_NAME"
-printf " - PROJECT_PATH=%s\n" "$PROJECT_PATH"
-printf " - BUILD_TARGET=%s\n" "$BUILD_TARGET"
-printf " - BUILD_VERSION=%s\n" "$BUILD_VERSION"
+printf " - PROJECT_PATH=%s\n"     "$PROJECT_PATH"
+printf " - BUILD_TARGET=%s\n"     "$BUILD_TARGET"
+printf " - BUILD_VERSION=%s\n"    "$BUILD_VERSION"
+printf " - BUILD_TMP_DIR=%s\n"    "$BUILD_TMP_DIR"
+printf " - ARCHIVE_DST_PATH=%s\n" "$ARCHIVE_DST_PATH"
 
+# Build the go binary
 cd "$PROJECT_PATH"
-mkdir out
-go build -ldflags "-s -w -X 'main.Version=#{version}'" -o out/$PROJECT_NAME
-cp -r doc out/doc
-
-# --------------------------------------------------------------------------------------------
-# Tar the source files
-tar -czf "$BUILD_TARGET" out/*
-rm -r out
-if [ ! -f "$BUILD_TARGET" ]; then
-  printf "ERROR: - build_script ${0} failed to tar source files from $PROJECT_PATH to $BUILD_TARGET\n"
-  cd "$INIT_DIR"
+go build -ldflags "-s -w -X 'main.Version=#{version}'" -o "$BUILD_TMP_DIR/$PROJECT_NAME"
+go_build_exit_code=$?
+if [ $go_build_exit_code -ne 0 ]; then
+  printf "ERROR: - ${PROJECT_NAME} go build failed with exit code $go_build_exit_code\n"
   return 2
 fi
-cd "$INIT_DIR"
+
+cp -r doc "$BUILD_TMP_DIR/doc"
+cp_exit_code=$?
+if [ $cp_exit_code -ne 0 ]; then
+  printf "ERROR: - ${PROJECT_NAME} cp doc failed with exit code=$cp_exit_code\n"
+  return 2
+fi
+
+# Tar the temporary build directory to the out directory specified with $2
+cd "$BUILD_TMP_DIR"
+tar -czf $ARCHIVE_DST_PATH *
+tar_exit_code=$?
+if [ $tar_exit_code -ne 0 ]; then
+  printf "ERROR: - ${PROJECT_NAME} tar failed with exit code $tar_exit_code\n"
+  return 2
+fi
+if [ ! -f "$ARCHIVE_DST_PATH" ]; then
+  printf "ERROR: - ${PROJECT_NAME} pack failed to generate tar archive at $ARCHIVE_DST_PATH\n"
+  return 2
+fi
+printf "%s\n" "$ARCHIVE_DST_PATH"
 return 0
